version: "3"
services:
  web-note:
    build: .
    container_name: web-note
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./data:/var/www/html/_tmp
    # environment:
    #  FILE_LIMIT: 100000 # the number of files limit (default: 100000)
    #  SINGLE_FILE_SIZE_LIMIT: 102400 # single file size limit, unit: byte (default: 102400)

volumes:
  web-note:
