version: "3"
services:
  web-note:
    image: ghcr.io/Lincest/web-note:latest
    container_name: web-note
    restart: always
    ports:
     - "80:80"
    volumes:
     - ./data:/var/www/html/_tmp

volumes:
  web-note:
