#!/bin/sh
set -e

# Create save path
case "${MWN_SAVE_PATH:=_tmp}" in
  /*) NOTES_PATH="$MWN_SAVE_PATH" ;;
  *) NOTES_PATH="/var/www/html/$MWN_SAVE_PATH" ;;
esac

# Ensure the directory exists and has correct permissions
if [ ! -d "$NOTES_PATH" ]; then
    mkdir -p "$NOTES_PATH"
fi

# Only copy .htaccess if it doesn't exist
if [ ! -f "$NOTES_PATH/.htaccess" ]; then
    cp "/var/www/html/notes.htaccess" "$NOTES_PATH/.htaccess"
fi

# Run default entrypoint
exec docker-php-entrypoint "$@"